### PR TITLE
Add 3He to ParticleData.xml

### PR DESCRIPTION
**Pull request by njacazio**

### CODE REVIEW

**Comment by njacazio** [comment]
@preghenella would it be ok?

**Comment by preghenella** [comment]
@njacazio 
it might be ok, but I would have this in the official pythia8 code.
because at the next pythia8 release your commit might be lost.

**Comment by njacazio** [comment]
Ok, thanks ! I will see for alternatives

**Comment by njacazio** [comment]
We handle this fully in the DelphesO2, thanks Roberto!

**Pull request closed without merging**
